Automated rollback of commit fc3edc67433192d4742d80de49a6ffbb58e76d63.
*** Reason for rollback ***

Breaks builds for physical device targets running OS versions that do not directly map to floats, e.g. on my phone running iOS 15.6.1:

ValueError: could not convert string to float: '15.6.1'

*** Original change description ***

Update the Info.plist mtime of any embedded bundles after copying the Bazel build artifacts over to DerivedData. This matches Xcode behavior and more importantly prevents an issue on iOS 16 or newer devices where incrmeental installations fail due to delta bundles not having a bundle ID because they don't have an Info.plist.

PiperOrigin-RevId: 478566431
(cherry picked from commit b748e0ab3cad1fb681de44a0a028bfccb0681940)